server:
  port: 8080

#management:
#  server:
#    port: 8080
#    address: 127.0.0.1
#  endpoint:
#    web:
#      expose: include=*


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  ldap: # 스프링부트의 임베디드 LDAP서버 설정 - 내부 개발 목적
    embedded:
      ldif: classpath:test-server.ldif # 리소스 디렉토리
      base-dn: dc=springframework,dc=org
      port: 8389

  servlet:
    multipart:
      max-file-size: 128KB # 최대 크기 제한
      max-request-size: 128KB # formData 요청 크기 제한

  redis:
    host: localhost
    port: 6379

  artemis:
    mode: embedded

storage:
  location: D:\someDirectory


