server:
#  port: 8761 # 유레카
  port: 8080

#management:
#  server:
#    port: 8080
#    address: 127.0.0.1
#  endpoint:
#    web:
#      expose: include=*


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  ldap: # 스프링부트의 임베디드 LDAP서버 설정 - 내부 개발 목적 ( 시큐리티 )
    embedded:
      ldif: classpath:test-server.ldif # 리소스 디렉토리
      base-dn: dc=springframework,dc=org
      port: 8389

  servlet:
    multipart:
      max-file-size: 128KB # 최대 크기 제한
      max-request-size: 128KB # formData 요청 크기 제한

  redis:
    host: localhost
    port: 6379

  artemis:
    mode: embedded

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    throw-exception-if-no-handler-found: true

  # json pretty-printed
  jackson:
    serialization:
      indent_output: true


storage:
  location: D:\someDirectory

# @Value 또는 @ConfigurationProperties 을 사용하여 설정을 가져갈 수 있습니다.
cors:
  allowed-origins:
    - http://localhost:8080
    - http://another-example.com
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE

# spring cloud
#eureka:
#  client:
#    register-with-eureka: false # 자신을 유레카 서버에 등록하지 않도록
#    fetch-registry: false # 유레카 서버가 다른 유레카 서버 서비스 목록을 가져오지 않도록
#
#logging:
#  level:
#    com.netflix.eureka: OFF
#    com.netflix.discovery: OFF
