server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git: 
          uri: ${USERPROFILE}/Desktop/config2  # 로컬 저장소

# github의 저장소를 사용할 경우
# https://github.com/spring-cloud-samples/config-repo 

#   application:
#     name: myConfig