server:
  port: 8888

springcloud:
  config:
    server:
      git:
        uri: ${HOME}/Desktop/config
  # 해당 디렉토리의 properties 또는 yml 파일의 정보도 읽어서 가져올 수 있습니다.

spring:
  application:
    name: application
# 위 설정이 없다면 properties 혹은 yml 의 이름을 사용